" Some random defaults
set number
set shiftwidth=2
set expandtab
set foldmethod=indent
set foldlevel=99
set incsearch
set hlsearch

filetype plugin indent on
syntax on

" Make the folded lines not so bright so my eyes dont hurt
hi Folded       guifg=grey guibg=darkblue ctermfg=grey ctermbg=darkblue

"""""""" Plugin stuff

"" CTRLP
set runtimepath^=~/.vim/bundle/ctrlp.vim
nmap <SPACE> :CtrlP<CR>


"""""""" Helpful commands

" Run this for xml highlighting: !xmllint --noout %

