execute pathogen#infect()

" Some random defaults
set number
set shiftwidth=2
set expandtab
set foldmethod=indent
set foldlevel=99
set incsearch
set hlsearch

filetype plugin indent on
syntax on

" Make the folded lines not so bright so my eyes dont hurt
hi Folded       guifg=grey guibg=darkblue ctermfg=grey ctermbg=darkblue

"""""""" Plugin stuff

""" open FuzzyFinder to pattern search
nmap <SPACE> :FufFile<CR>A**/<backspace>

" Run this for xml highlighting: !xmllint --noout %
